openapi: "3.0.0"
info:
  version: 0.0.1
  title: Software Interattivo

paths:
  /test:
    get:
      summary: Ricerca test
      description: Ricerca
      operationId: testGet
      parameters:
        - name: test
          description: test
          in: query
          required: true
          schema:
            type: string
          example: "FN261XE"
      responses:
        '200':
          description: test
          content:
            application/json:
              schema:
                $ref: "./entities.yaml#/Test"
        '400':
          $ref: './responses.yaml#/BadRequest'
        '404':
          $ref: './responses.yaml#/NotFound'
        default:
          $ref: './responses.yaml#/GenericError'
  /three-days-forecast/{country}/{city}:
    get:
      summary: Three days forecast
      description: Three days forecast
      operationId: getThreeDaysForecast
      parameters:
        - in: path
          name: country
          description: country
          required: true
          schema:
            type: string
            default: IT
        - in: path
          name: city
          description: city
          required: true
          schema:
            type: string
            default: Milan
      responses:
        '200':
          description: Three days forecast
          content:
            application/json:
              schema:
                $ref: "./entities.yaml#/ThreeDaysForecast"
        '400':
          $ref: './responses.yaml#/BadRequest'
        '404':
          $ref: './responses.yaml#/NotFound'
        default:
          $ref: './responses.yaml#/GenericError'