openweather:
  url: api.openweathermap.org/data/2.5/forecast
  workinghours: [9, 18]
server:
  port: 8080   # HTTP (Tomcat) port
endpoints:
  shutdown:
    enabled: false
    sensitive: false
logging:
  level:
    root: INFO
spring:
  application:
    name: tinyweatherbulletin-api
